pipeline:
  push_to_dev:
    image: limestreet/apache-php-7
    environment:
    commands:
      #- $DRONE_TAG
      - git config --global user.email "$DOCKER_EMAIL"
      #- git reset --hard
      #- git clean -f
      - VERSION_LINE=$(grep -Po "Version:\s?\s?\d\d?\.\d\d?\.?\d?\d?.*" $PWD/style.css)
      #- echo $VERSION_LINE
      - VERSION=$(echo $VERSION_LINE | grep -Po "\d\d?\.\d\d?\.?\d?\d?")
      #- VERSION=`grep -Po "(\d\d?\.\d\d?\.\d\d?)" <<< "$VERSION_LINE"`
      - sed -i "s/$VERSION_LINE/Version:\ $VERSION+build$DRONE_BUILD_NUMBER/" $PWD/scss/underscores/style.scss
      - sed -i "s/$VERSION_LINE/Version:\ $VERSION+build$DRONE_BUILD_NUMBER/" $PWD/style.css
      #- COMPOSER_THEME_VERSION_LINE=$(grep -Po '"version"\s?\s?:\s?\s?"\d\d?\.\d\d?\.\d\d?.*"' $PWD/composer.json)
      #- echo $COMPOSER_THEME_VERSION_LINE
      #- COMPOSER_THEME_VERSION=$(echo $COMPOSER_THEME_VERSION_LINE | grep -Po "(\d\d?\.\d\d?\.\d\d?)")
    #- COMPOSER_THEME_VERSION=`grep -Po "(\d\d?\.\d\d?\.?\d?\d?)" <<< "$COMPOSER_THEME_VERSION_LINE"`
      #- sed -i "s/$COMPOSER_THEME_VERSION_LINE/\"version\"\ :\ \"$COMPOSER_THEME_VERSION+build$DRONE_BUILD_NUMBER\"/" $PWD/composer.json
      #- cat composer.json
      #- git fetch
      #- git status
      - npm install --silent
      - git add .
    #- git status
      - git commit -m "Drone build nr $DRONE_BUILD_NUMBER [CI SKIP]"
      - git checkout -b dev
      - git merge master
      - git push origin dev --force
    #- git push origin/beta
    secrets: [ DOCKER_EMAIL ]
    when:
      event: push
      #branch:
      #  exclude: dev

  performancetest:
    image: limestreet/apache-php-7
    environment:
    commands:
    #- ls -la
    #- printenv
    - THEME_SLUG=$DRONE_REPO_NAME
    - THEME_LOW=`echo "$THEME_SLUG" | sed 's/-by-fat//'`
    #- echo $THEME_LOW
    #- echo $PWD
    #- THEME_NAME=`echo "$THEME_LOW" | sed 's/\b\w/\U&/'`
    #- npm install --silent
    - sleep 15
    - REMOTEURL="http://$THEME_LOW.dev.limestreet.pl/wp-content/themes/$THEME_SLUG/style.css"
    #- echo $REMOTEURL
    - REMOTEVERSION=$(curl $REMOTEURL | grep -Po "Version:\s?\s?\d\d?\.\d\d?\.?\d?\d?.*" | grep -Po "(\d\d?\.\d\d?\.?\d?\d?.*)")
    - echo $REMOTEVERSION
    - LOCALVERSION=$(cat style.css | grep -Po "Version:\s?\s?\d\d?\.\d\d?\.?\d?\d?.*" | grep -Po "(\d\d?\.\d\d?\.?\d?\d?.*)")
    - echo $LOCALVERSION
    - if [ $REMOTEVERSION != $LOCALVERSION ]; then echo "Wrong theme version - $REMOTEVERSION instead of $LOCALVERSION" && exit 1 ;fi
    - sed -i "s/THEME_SLUG/$THEME_SLUG/g" ./Gruntfile.js
    - pa11y -V
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/sample-page/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/?s=post
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/?s=gergeafer
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/gergeafer
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/2013/01/10/markup-image-alignment/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/2013/01/11/markup-html-tags-and-formatting/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/category/aciform/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/2012/01/03/template-comments/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/author/patryk/
    #- pa11y --ignore "warning;notice" http://$THEME_SLUG.dev.limestreet.pl/tag/template/
    - grunt pagespeed
    - grunt perfbudget
    when:
      event: push
      #branch:
      #  exclude: dev
      
services:
  database:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=wp
      - MYSQL_DATABASE=wordpress_test
